version: '3.8'

services:
  jupyter:
    image: quay.io/jupyter/scipy-notebook:python-3.13
    container_name: jupyter_notebook
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes  # If you want JupyterLab instead of classic notebook
      - NB_UID=501 # Set UID and GID to your local uid and gid
      - NB_GID=20
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''